### ISSUE TITLE
Create models/collection from request

### ISSUE THREAD

**Issue by manuelmeurer** [lanej/cistern#22]
I really like the cistern approach but a quickstart guide that explains the basic functionalities would be nice.
I'm happy to contribute this once my first API wrapper is done. :)

How do I create/return models or a collection for a request?
I created a request that fetches a list of items (e.g. like this: https://github.com/lanej/zendesk2/blob/master/lib/zendesk2/client/requests/get_tickets.rb) but it returns a `Faraday::Response` right now (I use Faraday like the zendesk2 gem). How do I make it return a collection object?

On top of that, the response looks like this:

```
{
  query: "stuff",
  items: 10,
  accesskey: "123",
  operation: "itemsearch",
  page: 1
},
items: {
  totalresults: 356,
  totalpages: 36,
  item: [
    {
      item data
    },
    ...
```

How can I extract the `totalresults` and `totalpages` fields as well?

Thanks for a great gem! :)

**Comment by lanej** [comment]
Long time for this, but I've decided to not support this due to differing ways of services choose to paging (cursors, paging attributes, tokens, etc).

I do think adding a bit of documentation discussing it though would be worthwhile.
