### ISSUE TITLE
Cistern::Model#new_record? raises TypeError when @identity is not set with 2.0.3

### ISSUE THREAD

**Issue by drbrain** [lanej/cistern#48]
As in #47 the documentation says identity is ["not required"](https://github.com/lanej/cistern/blob/master/README.md#attributes) but if you don't have it defined you get an unhelpful error when you call #new_record? on a `Model` instance:

```
$ ruby -e 'gem "cistern", "= 2.0.3"; require "cistern"; class MyService < Cistern::Service; end; p Cistern::VERSION; p MyService::Model.new.new_record?'
"2.0.3"
/…/gems/cistern-2.0.3/lib/cistern/attributes.rb:176:in `identity': nil is not a symbol nor a string (TypeError)
	from /…/gems/cistern-2.0.3/lib/cistern/attributes.rb:225:in `new_record?'
	from -e:1:in `<main>'
```

This behavior is new in 2.0.3 and did not exist in 2.0.2:

```ruby
$ ruby -e 'gem "cistern", "= 2.0.2"; require "cistern"; class MyService < Cistern::Service; end; p Cistern::VERSION; p MyService::Model.new.new_record?'
"2.0.2"
```

*PS*
The service we're wrapping has a compound identifier so `Cistern::Attributes::identity` is insufficient. I can work around this bug in the mean time, though.

**Comment by lanej** [comment]
@drbrain interesting. haven't considered a identity as a composite attribute.

i can fix this relatively easily but I'd like to noodle on the implications of bundling multiple attributes into an identity

**Comment by lanej** [comment]
https://github.com/lanej/cistern/releases/tag/v2.0.4 has the fix

**Comment by drbrain** [comment]
Many thanks!

No worries on the compound id, I worked around this bug by overriding #new_record? and having it check for a creation timestamp.
